// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiastueclkzyfggvgbju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpYXN0dWVjbGt6eWZnZ3ZnYmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MjI1MjQsImV4cCI6MjA1MjM5ODUyNH0.HK56vF7-nxM4LIcT5Zqg2I1VHOzP30Ku7qOhc1_sNd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);